version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: bootcamp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    networks:
      - bootcamp-network
      
  node-app:
    build: .
    image: bootcamp-node-api:latest
    container_name: bootcamp-node-api
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - bootcamp-network

networks:
  bootcamp-network:
    driver: bridge